packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/documentation'
  - 'packages/storybook'
  - 'packages/lib/components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
