name: Create Pull Request

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:
      # Ignore main branch
      - 'master'

jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v3

      # Create Pull Request
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'New changes from ${GITHUB_REF##*/}'
          base: 'master'
          # Change 'master' to your primary branch if necessary
          branch: 'automated-pr/${{ github.head_ref }}'
          delete-branch: true
          # Adding some default labels
          labels: 'auto-pr'
          # Draft pull requests are not considered to be ready for review
          draft: true
